version: "3.8"

services:
  web-api:
    build: .
    container_name: web-api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5027:80"
    environment:
      - SqlKey=Host=database;Port=5432;Database=compete;Username=compete-user;Password=compete-user-password;Include Error Detail=true;
      - SteamApiKey=AB4812231FDF1B99CDDE317137E0794D
      - ServiceKey=PeterPARKERhaha
      - Host=https://compete.wtf
      - ShopId=414697
      - AgentId=506341
      - PayoutKey=test_*gN85TQfBRSDPhW2XopO_q2iaGi1vK9uzNJpUptbnxnyU
      - PaymentKey=test_TWZPeXFe7sMm1Y5ZbZnIEKQVaYmRQLQ-16CqAEpXc8U
      - Redis=redis:6379,abortConnect=false
      - JwtKey=ITGKii5iIIGMk45kmhkM4Kmgik4iiKKDKo4oiktkkskmkqm5645jhVBCVBDFvmo
      - Issuer=compete
      - ServerManagingAccessKey=hfgik7U65JMmkmbgikbi4
      - YMoneyNotificationKey=zHCGekfxli0MVotwo407i66Q
    volumes:
      - ~/api/compete-platform/UploadedFiles:/app/UploadedFiles
    depends_on:
      - database
      - redis
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: compete
      POSTGRES_USER: compete-user
      POSTGRES_PASSWORD: compete-user-password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
